### ISSUE TITLE
Erroneous behaviour when omitting an output directory in the sbt run command.

### ISSUE THREAD

**Issue by fmv1992** [tizuck/scala-uml#18]
Can you provide a `sbt run` example from the CLI? I get a bunch of debug messages but zero output files.

**Comment by tizuck** [comment]
I think in the last month some changes to the scala-meta API have been processed leading to a bug when trying to use the current version. I will fix this as soon as possible. Thank you!

**Comment by fmv1992** [comment]
Is there a way to use it as is? Like a valid commit? The idea looks promising.

Thanks for making this program available.

**Comment by tizuck** [comment]
Yes there is a way to use the sofware in the current state. I discovered that the bug occurs when you don't specify an output directory for the image/.puml file. 

If you want to get a .puml file of the source code for this project for example you can do it using the following command:
**sbt "run --fp src/main/scala/uml --t --d dia --n foo"**
This will produce a **foo.puml** file with the resulting diagram of all scala files contained in the  ***src/main/scala/uml*** directory
